# Generated by Django 6.0.4 on 2026-05-04 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='project',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='value',
        ),
        migrations.AddField(
            model_name='measurement',
            name='temperature',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='measurement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurements.sensor'),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
